#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"

Mailman.config.logger = Logger.new("log/mailman.log")

Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true,
  username: "radwebsitemanagers@gmail.com",
  password: "123website"
}

Mailman::Application.run do
  default do
    begin
      #Ticket.receive_mail(message)
      Mailman.logger.error "received email:\n#{message}"
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
